UserManager\ForgotPasswordBundle\Entity\ForgotPassword:
    type: entity
    table: forgot_password
    repositoryClass: UserManager\ForgotPasswordBundle\Entity\ForgotPasswordRepository
    indexes:
        fp_key_index:
            columns: [ fp_key ]
        id_login_index:
            columns: [ id_login ]
    fields:
        id:
            type: bigint
            id: true
            generator: { strategy: AUTO }
        fp_key:
            type: string
            length: 64
            unique: true
            nullable: false
        id_login:
            type: bigint
            nullable: false
        created_at:
            type: datetime
        updated_at:
            type: datetime
            nullable: true            
    manyToOne:
        Login:
          targetEntity: UserManager\LoginBundle\Entity\Login
          inversedBy: ForgotPassword
          joinColumn:
            name: id_login
            referencedColumnName: id
            onDelete: CASCADE
            onUpdate: CASCADE
          cascade: [ persist ]            
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]            