userprofile:
    path:     /
    defaults: { _controller: "UserManagerUserProfileBundle:UserProfile:index" }

userprofile_show:
    path:     /{id}/show
    defaults: { _controller: "UserManagerUserProfileBundle:UserProfile:show" }

userprofile_new:
    path:     /new
    defaults: { _controller: "UserManagerUserProfileBundle:UserProfile:new" }

userprofile_create:
    path:     /create
    defaults: { _controller: "UserManagerUserProfileBundle:UserProfile:create" }
    methods:  POST

userprofile_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserManagerUserProfileBundle:UserProfile:edit" }

userprofile_update:
    path:     /{id}/update
    defaults: { _controller: "UserManagerUserProfileBundle:UserProfile:update" }
    methods:  [POST, PUT]

userprofile_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserManagerUserProfileBundle:UserProfile:delete" }
    methods:  [POST, DELETE]
